version: 2

build:
  tools:
    python: "3.10"

sphinx:
  configuration: docs/conf.py
  # sphinx.fail_on_warning: true

python:
  install:
  - method: pip
    path: .
    extra_requirements:
      - docs
